<div id="header" data-cmsadmin-layout-header="true">
    <h1 style="float:left" data-cmsadmin-layout-branding="true"><$logo href="/" maxwidth="900" maxheight="450" alt=""$><a href="/"><img src="template/wildfrog-logo-trans.png" alt="" border="0" /></a><$/logo$></h1>
    </div>
    <div id="navigation" data-cmsadmin-layout-nav="true">
        <$globalmenu cssClass="mainNav" showLevels="1" alwaysShowChildren="false" showHome="true"/$>
    </div>