<div id="footer" data-cmsadmin-layout-footer="true">	
			
		<div id="footerLeft">		
			<$globalmenu cssClass="footerNav" showLevels="1" alwaysShowChildren="false" showHome="true"/$>

<!--			
			<div id="socialMedia">
					<a href="http://www.twitter.com"><img src="images/icon-twitter.gif" width="67" height="20" alt="" /></a>
					<a href="http://www.facebook.com"><img src="images/icon-facebook.gif" width="73" height="20" alt="" /></a>
					<a href="http://www.myspace.com"><img src="images/icon-myspace.gif" width="75" height="20" alt="" /></a>
			</div>
-->
		</div>
		
		<div class="copyright">
			&copy; <$date format="yyyy"/$> <$websitename/$>. All rights reserved.<br />
			<div id="poweredBy"><$poweredby/$></div>
		</div>	
		
		<ul class="privacy">
			<li><a href="/">Home</a></li>
			<li><a href="/sitemap/">Sitemap</a></li>
			<li><a href="#body">Back to Top</a></li>
		</ul>
		
		<br class="clear" />		
	</div>